docker:
  image: yegor256/rultor-image:1.22.0
assets:
  docker-password: yegor256/home#assets/docker-password
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    repo=yegor256/squid-proxy
    sed -i -e "s/^0.0.0/${tag}/" Dockerfile
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${repo}:${tag}"